
services:
  techietoxpress:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./techietoxpress:/techietoxpress
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY="django-insecure-)llyy_56vbb(#(xi@z8(qkcamhiva4e%65gbq2f&d@8tn53)5x"
      - DEBUG=1
      

  
  
