# docker-compose.yml

version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=techietoxpress
      - POSTGRES_USER=techietoxpress
      - POSTGRES_PASSWORD=techietoxpress

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/techietoxpress
    ports:
      - "8001:8000"
    depends_on:
      - db



  
  
