
services:
  techietoxpress:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY="django-insecure-)llyy_56vbb(#(xi@z8(qkcamhiva4e%65gbq2f&d@8tn53)5x"

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - techietoxpress
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
volumes:
  static-data:

      

  
  
